version: '1.0'

networks:
  data_network: #orange
    driver: bridge
  service_action_network: #pink
    driver: bridge
  service_info_network: #blue
    driver: bridge
  service_registry_network: #green
    driver: bridge
  front-register_network: #red
    driver: bridge
  main-backup_network:
    driver: bridge 

services:
  pg:
    build: 
      context: ./SOA_postgres
      args:
        - TAG=pg-latest
    ports:
      - "4006:4006"
    networks:
      - data_network

  pastyields:
    build: 
      context: ./SOA_pastYields
      args:
        - TAG=pastyields-latest
    ports:
      - "4000:4000"
    networks:
      - service_action_network
      - data_network
      - service_info_network

  datadisplayer:
    build:
      context: ./SOA_dataDisplayer
      args:
        - TAG=datadisplayer-latest
    ports:
      - "4001:4001"
    networks:
      - service_action_network
      - data_network
      - service_info_network

  ranker:
    build: 
      context: ./SOA_rankbysector
      args:
        - TAG=ranker-latest
    ports:
      - "4002:4002"
    networks:
      - service_action_network
      - data_network
      - service_info_network

  registry:
    build: 
      context: ./SOA_registry
    ports:
      - "4004:4004"
    networks:
      - service_registry_network
      - front-register_network
  
  backupregistry:
    build: ./SOA_backupregistry
    ports:
      - "4005:4005"
    networks:
      - service_registry_network
      - front-register_network
      - main-backup_network

  provider:
    build: 
      context: ./SOA_provider
      args:
        - TAG=provider-latest
    ports:
      - "4003:4003"
    networks:
      - service_info_network
      - service_registry_network
      - main-backup_network

  frontend:
    build: 
      context: ./SOA_frontend/soa_client
      args:
        - TAG=latest
    ports:
      - "3000:3000"
    networks:
      - front-register_network

  frontend-server:
    build: 
      context: ./SOA_frontend/SOA_server
      args:
        - TAG=frontend-server-latest
    ports:
      - "3001:3001"
    networks:
      - front-register_network
      - service_action_network
